language: java
jdk:
  - openjdk11
env:
  - PROTOBUF_VER="3.14.0"

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - mkdir -p $HOME/protobuf && pushd $HOME/protobuf
    && curl -LO https://github.com/google/protobuf/releases/download/v$PROTOBUF_VER/protoc-$PROTOBUF_VER-linux-x86_64.zip
    && unzip protoc-$PROTOBUF_VER-linux-x86_64.zip
    && popd
  - export PATH=$HOME/protobuf/bin:$PATH

before_script:
  - echo $HOME
  - echo $JAVA_HOME
  - protoc --version
  - ./gradlew autoLintGradle
  - ./gradlew verifyChecksums

script:
  - ./gradlew check -PtestcontainerTest