spring.docker.compose:
  enabled: true
  file: ./../../docker/regtest/lightning-regtest-setup-devel/docker-compose.yml
  stop.command: DOWN # STOP is default, DOWN clears all container data after shutdown
  skip.in-tests: false

org.tbk.bitcoin.jsonrpc:
  network: regtest
  rpchost: http://localhost
  rpcport: 18443
  rpcuser: regtest-rpc-user
  rpcpassword: regtest-rpc-pass

org.tbk.lightning.cln.grpc:
  enabled: false # all beans are created programmatically
